AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for NEOGOVLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  NEOGOVLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/NEOGOVLambda/
      Handler: NEOGOVLambda::NEOGOVLambda.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        NEOGOVLambda:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /NEOGOVLambda
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NEOGOVLambdaApi:
    Description: "API Gateway endpoint URL for Prod stage for NEOGOVLambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/NEOGOVLambda/"
  NEOGOVLambdaFunction:
    Description: "NEOGOVLambda Lambda Function ARN"
    Value: !GetAtt NEOGOVLambda.Arn
  NEOGOVLambdaIamRole:
    Description: "Implicit IAM Role created for NEOGOVLambda function"
    Value: !GetAtt NEOGOVLambdaRole.Arn
